---
- name: Create resource group for the app and plan
  azure_rm_resourcegroup:
    name: "{{ az_resource_group }}"
    location: "{{ az_region }}"
- name: Create resource group for the Key vault
  azure_rm_resourcegroup:
    name: "virtualmonitor-keyvault-rg"
    location: "{{ az_region }}"
