---
- name: Create App Service Plan
  azure_rm_appserviceplan:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_webapp_plan }}"
    location: "{{ az_region }}"
    is_linux: true
    sku: S1
    number_of_workers: 1
- name: Create App Service on Linux
  azure_rm_webapp:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_webapp }}"
    plan: "{{ az_webapp_plan }}"
#- name: Activate deployment from docker registry
#  command: "az webapp config container set -n {{ az_webapp }} -g {{ az_resource_group }} --docker-custom-image-name hsldevcom/digitransit-{{ az_project }}:{{ docker_tag }} --docker-registry-server-user  {{ username }} --docker-registry-server-password {{ passwd }}"
- name: Activate deployemnt from Github Actions
  command: "az webapp deployment github-actions add --repo HSLdevcom/digitransit-virtualmonitor -g {{ az_resource_group }} -b next -n {{ az_webapp }} --token {{ github_token }}"
- name: Activate logging
  command: "az webapp log config -n {{ az_webapp }} -g {{ az_resource_group }} --web-server-logging filesystem"
- name: Activate System managed identity
  command: "az webapp identity assign -n {{ az_webapp }} -g {{ az_resource_group }}"
#- name: Create Key Vault
#  command: "az keyvault create --name {{ keyvault_name }} --resource-group virtualmonitor-keyvault-rg --location {{ az_region }}"
#- name: Create Secret DB_CONTAINER
#  command: "az keyvault secret set --vault-name {{ keyvault_name }} --name db-container --value {{ keyvault_db_container }}"
#- name: Create Secret DB_ENDPOINT_DEV
#  command: "az keyvault secret set --vault-name {{ keyvault_name }} --name db-endpoint-dev --value {{ keyvault_db_endpoint_dev }}"
#- name: Create Secret DB_ID_DEV
#  command: "az keyvault secret set --vault-name {{ keyvault_name }} --name db-id-dev --value {{ keyvault_db_id_dev }}"
#- name: Create Secret DB_KEY_DEV
#  command: "az keyvault secret set --vault-name {{ keyvault_name }} --name db-key-dev --value {{ keyvault_db_key_dev }}"
- name: Get Web app Service principal id
  command: "az webapp identity show --name {{ {{ az_webapp }} }} --resource-group {{ az_resource_group }} --query principalId -o tsv"
  register: out
- name: Assign Privilages to Key vault
  command: "az keyvault set-policy --name {{ keyvault_name }} --object-id {{ out.stdout_lines.0 }} --secret-permissions get list"
- name: Set DB_CONTAINER Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_CONTAINER={{ db_container }}"
- name: Set DB_ENDPOINT Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_ENDPOINT={{ db_endpoint_dev }}"
- name: Set DB_ID Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_ID={{ db_id_dev }}"
- name: Set DB_KEY Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_KEY={{ db_key_dev }}"
