---
- name: Create App Service Plan
  azure_rm_appserviceplan:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_webapp_plan }}"
    location: "{{ az_region }}"
    is_linux: true
    sku: S1
    number_of_workers: 1
- name: Create App Service on Linux
  azure_rm_webapp:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_webapp }}"
    plan: "{{ az_webapp_plan }}"
    #### CURRENTLY IN PREVIEW (10/21)
#- name: Activate deployment from Github Actions
#  command: "az webapp deployment github-actions add  --token {{ github_token }} --repo <HSLdevcom/repo-name> -g {{ az_resource_group }} -b <branch> -n {{ az_webapp }}"
    #######
- name: Activate logging
  command: "az webapp log config -n {{ az_webapp }} -g {{ az_resource_group }} --web-server-logging filesystem"
- name: Activate System managed identity
  command: "az webapp identity assign -n {{ az_webapp }} -g {{ az_resource_group }}"
- name: Add development slot
  command: "az webapp deployment slot create --name  {{ az_webapp }} --resource-group {{ az_resource_group }} --slot dev"
- name: Create Key Vault
  command: "az keyvault create --name {{ keyvault_name }} --resource-group {{ az_keyvault_rg }} --location {{ az_region }}"
  ## Secret creation example
#- name: Create Secret FOO
#  command: "az keyvault secret set --vault-name {{ keyvault_name }} --name <secret-name> --value <secret value>"
- name: Get Web app Service principal id
  command: "az webapp identity show --name {{ az_webapp }} --resource-group {{ az_resource_group }} --query principalId -o tsv"
  register: out
- name: Assign Privilages to Key vault
  command: "az keyvault set-policy --name {{ keyvault_name }} --object-id {{ out.stdout_lines.0 }} --secret-permissions get list"
- name: Set DB_CONTAINER Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_CONTAINER={{ db_container }}"
- name: Set DB_ENDPOINT Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_ENDPOINT={{ db_endpoint_dev }}"
- name: Set DB_ID Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_ID={{ db_id_dev }}"
- name: Set DB_KEY Setting
  command: "az webapp config appsettings set --name {{ az_webapp }} --resource-group {{ az_resource_group }} --settings DB_KEY={{ db_key_dev }}"
